# Generated by Django 3.0.5 on 2020-04-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='rules',
            field=models.CharField(max_length=800),
        ),
    ]
