# Generated by Django 3.0.5 on 2020-04-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20200409_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rules',
            field=models.CharField(max_length=200),
        ),
    ]
