# Generated by Django 3.0.5 on 2020-04-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20200413_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rules',
            field=models.TextField(max_length=200),
        ),
    ]
