# Generated by Django 3.0.5 on 2020-05-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20200513_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
        migrations.AddField(
            model_name='house',
            name='house_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
