# Generated by Django 3.0.5 on 2020-04-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20200413_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='rules',
        ),
    ]
