# Generated by Django 3.0.5 on 2020-04-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_remove_house_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rules',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
