# Generated by Django 3.0.5 on 2020-05-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20200518_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='postcode',
            new_name='address',
        ),
    ]
