# Generated by Django 3.0.5 on 2020-04-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
