# Generated by Django 3.0.4 on 2020-04-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('beginTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Room')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
