# Generated by Django 3.0.5 on 2020-04-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_auto_20200417_1600'),
        ('bookings', '0002_auto_20200417_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.Utility'),
        ),
    ]
