# Generated by Django 3.0.5 on 2020-04-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20200417_1601'),
        ('bookings', '0002_auto_20200417_1745'),
    ]

    operations = [
    ]
