# Generated by Django 3.0.5 on 2020-05-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_auto_20200524_1616'),
        ('bookings', '0005_auto_20200505_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.House'),
        ),
    ]
