# Generated by Django 3.0.5 on 2020-04-17 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chores', '0002_auto_20200417_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.House'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
