# Generated by Django 3.0.5 on 2020-04-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_auto_20200417_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
