# Generated by Django 3.0.5 on 2020-04-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utility',
            old_name='houseId',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='utility',
            old_name='isBookable',
            new_name='is_bookable',
        ),
    ]
