# Generated by Django 3.0.5 on 2020-04-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_nr', models.CharField(blank=True, max_length=11, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[(1, 'pending'), (2, 'assigned'), (3, 'unassigned')], max_length=15)),
                ('is_admin', models.BooleanField(default=False)),
                ('house_owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='houses.House')),
                ('house_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='houses.House')),
            ],
        ),
    ]
