# Generated by Django 3.0.4 on 2020-04-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='house_id',
        ),
        migrations.AddField(
            model_name='user',
            name='house_owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='houses.House'),
        ),
        migrations.AddField(
            model_name='user',
            name='house_tenant',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='houses.House'),
        ),
    ]
