# Generated by Django 3.0.5 on 2020-04-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_nr',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
