# Generated by Django 3.0.4 on 2020-04-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        ('users', '0002_auto_20200415_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='houses.House'),
        ),
    ]
