# Generated by Django 3.0.5 on 2020-04-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200417_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='house_owner',
        ),
    ]
