# Generated by Django 3.0.5 on 2020-04-19 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_owner'),
        ('users', '0006_remove_user_house_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='house_tenant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'pending'), (2, 'assigned'), (3, 'unassigned')], default=1, max_length=15)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
