# Generated by Django 3.0.5 on 2020-04-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_last_login'),
        ('users', '0008_remove_user_code'),
    ]

    operations = [
    ]
