# Generated by Django 3.0.5 on 2020-04-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
