# Generated by Django 3.0.5 on 2020-05-18 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20200513_0822'),
        ('custom_events', '0002_auto_20200417_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customevent',
            name='notify_admin',
        ),
        migrations.AddField(
            model_name='customevent',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.House'),
        ),
    ]
