# Generated by Django 3.0.5 on 2020-05-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_events', '0003_auto_20200518_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='notify_owner',
            field=models.BooleanField(default=False),
        ),
    ]
