# Generated by Django 3.0.5 on 2020-06-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_events', '0004_customevent_notify_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='from_owner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
